#!/bin/bash
for TEST in *_test.js; do
  echo -n "$TEST "

  exec 3>&1 4>&2
  RESULT=$( { node-fibers $TEST|grep _END_ 1>&3 2>&4; } 3>&1)
  exec 3>&- 4>&-

  if [[ $RESULT == "_END_" ]]; then
    echo -e "\E[32m\E[1mOK\033[0m"
  else
    echo -e "\E[31m\E[1mFAIL\033[0m"
  fi;   
done;

